branches:
  only:
    - main
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version 
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed m3afifi/udagram-api-feed:v5
  - docker tag udagram-api-user m3afifi/udagram-api-user:v5
  - docker tag reverseproxy m3afifi/reverseproxy:v5
  - docker tag udagram-frontend m3afifi/udagram-frontend:v5

after_success:
  - echo "$DOCKER_USERNAME"
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
  - docker push m3afifi/udagram-api-feed:v5
  - docker push m3afifi/udagram-api-user:v5
  - docker push m3afifi/reverseproxy:v5
  - docker push m3afifi/udagram-frontend:v5